name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  setup:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Julia environment
      - uses: julia-actions/setup-julia@v1.1.8

    
  
